In [44]:
import torch
print(torch.__version__)
if(torch.cuda.is_available()):
    print(torch.cuda.get_device_name(0))
    print(torch.cuda.is_available())
else:
    print("No GPU available")

2.5.1
No GPU available


## 1. TENSOR CREATION

-> For empty tensor

In [45]:
a = torch.empty(5, 3)
print(type(a))
print(a)

<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


-> For all the ones in tensor

In [46]:
a = torch.ones(5, 3)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


-> For Random values 

In [47]:
a = torch.rand(5, 3)
print(a)

tensor([[0.6726, 0.5740, 0.9233],
        [0.9178, 0.7590, 0.7775],
        [0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157],
        [0.6574, 0.3451, 0.0453]])


-> Manual Seed for reproducability of same random values.

In [48]:
torch.manual_seed(100)
torch.rand(5, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

In [49]:
torch.manual_seed(100)
torch.rand(5, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

-> Tensor from our given values.

In [50]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

-> Other ways to create tensors.

In [51]:
#arange for range
print(torch.arange(0, 10, 2)) #start, end, step

#lingspace for linear spacing
print(torch.linspace(0, 10, 5)) #start, end, number of points

#eye for identity matrix
print(torch.eye(3))

#full for filling tensor with a value
print(torch.full((2,3), 10))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[10, 10, 10],
        [10, 10, 10]])


## 2. TENSOR SHAPES

In [52]:
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [53]:
x.shape

torch.Size([2, 3])

In [54]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [55]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [56]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784]])

## 3. Datatypes

In [57]:
# find the datatype of the tensor
x.dtype

torch.int64

In [58]:
# assigning the datatype
x = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
x.dtype

torch.float32

In [59]:
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 4.  MATHEMATICAL OPERATIONS

* Scalar Operations

In [60]:
x = torch.rand(2,2)

In [61]:
x+2
x-2
x*2
x/2
x**2
(x*100)//3
((x*100)//3)%2

tensor([[1., 0.],
        [0., 0.]])

* Element wise Operation

In [62]:
a = torch.tensor([[1,2], [3,4]])
print(a)
b = torch.tensor([[10,20], [30,40]])
print(b)

tensor([[1, 2],
        [3, 4]])
tensor([[10, 20],
        [30, 40]])


In [63]:
#addition
print(a+b)
print(torch.add(a,b))

#subtraction
print(a-b)
print(torch.sub(a,b))

#multiplication
print(a*b)  
print(torch.mul(a,b))

#division
print(a/b)
print(torch.div(a,b))

#matrix multiplication
print(a@b)
print(torch.mm(a,b))

tensor([[11, 22],
        [33, 44]])
tensor([[11, 22],
        [33, 44]])
tensor([[ -9, -18],
        [-27, -36]])
tensor([[ -9, -18],
        [-27, -36]])
tensor([[ 10,  40],
        [ 90, 160]])
tensor([[ 10,  40],
        [ 90, 160]])
tensor([[0.1000, 0.1000],
        [0.1000, 0.1000]])
tensor([[0.1000, 0.1000],
        [0.1000, 0.1000]])
tensor([[ 70, 100],
        [150, 220]])
tensor([[ 70, 100],
        [150, 220]])


In [64]:
c = torch.tensor([-10,20,-30])

In [ ]:
#abs for absolute value
print(torch.abs(c))

tensor([10, 20, 30])


In [66]:
#negation
print(torch.neg(c))

tensor([ 10, -20,  30])


In [67]:
d = torch.tensor([1.2, 2.3, 3.4])

In [68]:
#rounding
print(torch.round(d))
#ceil
print(torch.ceil(d))
#floor
print(torch.floor(d))

tensor([1., 2., 3.])
tensor([2., 3., 4.])
tensor([1., 2., 3.])


## 5. REDUCTION OPERATIONS

In [69]:
e = torch.randint(0, 10, (2,3), dtype=torch.float32)
print(e)

tensor([[1., 9., 9.],
        [8., 0., 7.]])


In [70]:
#sum
print(torch.sum(e))
print(torch.sum(e, dim=0))  #column wise
print(torch.sum(e, dim=1))  #row wise

tensor(34.)
tensor([ 9.,  9., 16.])
tensor([19., 15.])


In [71]:
#mean
print(torch.mean(e.float()))
#median 
print(torch.median(e.float()))

tensor(5.6667)
tensor(7.)


In [72]:
#max and min values
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(0.)


In [73]:
#standard deviation
print(torch.std(e.float()))

tensor(4.0825)


In [74]:
#variance
print(torch.var(e.float()))

tensor(16.6667)


In [75]:
#argmax and argmin gives the index of the max and min values
print(torch.argmax(e))
print(torch.argmin(e))

tensor(1)
tensor(4)


## 6. COMPARISION OPERATIONS

In [76]:
i = torch.randint(0, 10, (2,3))
print(i)
j = torch.randint(0, 10, (2,3))
print(j)

tensor([[0, 0, 9],
        [5, 7, 3]])
tensor([[9, 4, 0],
        [5, 7, 5]])


In [77]:
# greater than
print(i>j)
print(torch.gt(i,j))

# greater than or equal to
print(i>=j)
print(torch.ge(i,j))

# less than
print(i<j)
print(torch.lt(i,j))

# less than or equal to
print(i<=j)
print(torch.le(i,j))

# equal to
print(i==j)
print(torch.eq(i,j))

# not equal to
print(i!=j)
print(torch.ne(i,j))

#logical and
print(torch.logical_and(i,j))

#logical or
print(torch.logical_or(i,j))

#logical not
print(torch.logical_not(i))

#logical xor
print(torch.logical_xor(i,j))

#concatenation
print(torch.cat((i,j), dim=0))

tensor([[False, False,  True],
        [False, False, False]])
tensor([[False, False,  True],
        [False, False, False]])
tensor([[False, False,  True],
        [ True,  True, False]])
tensor([[False, False,  True],
        [ True,  True, False]])
tensor([[ True,  True, False],
        [False, False,  True]])
tensor([[ True,  True, False],
        [False, False,  True]])
tensor([[ True,  True, False],
        [ True,  True,  True]])
tensor([[ True,  True, False],
        [ True,  True,  True]])
tensor([[False, False, False],
        [ True,  True, False]])
tensor([[False, False, False],
        [ True,  True, False]])
tensor([[ True,  True,  True],
        [False, False,  True]])
tensor([[ True,  True,  True],
        [False, False,  True]])
tensor([[False, False, False],
        [ True,  True,  True]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[ True,  True, False],
        [False, False, False]])
tensor([[ True,  True,  True],
        [False, False, False]]

## 7. SPECIAL FUNCTIONS

In [78]:
k = torch.randint(0, 10, (2,3))
print(k)

tensor([[9, 9, 7],
        [5, 9, 8]])


In [79]:
#log 
print(torch.log(k.float()))

#sqrt
print(torch.sqrt(k.float()))

#exp
print(torch.exp(k.float()))

#sigmoid
print(torch.sigmoid(k.float()))

#softmax
print(torch.softmax(k.float(), dim=0))

#relu
print(torch.relu(k.float()))

#tanh
print(torch.tanh(k.float()))

tensor([[2.1972, 2.1972, 1.9459],
        [1.6094, 2.1972, 2.0794]])
tensor([[3.0000, 3.0000, 2.6458],
        [2.2361, 3.0000, 2.8284]])
tensor([[8103.0840, 8103.0840, 1096.6332],
        [ 148.4132, 8103.0840, 2980.9580]])
tensor([[0.9999, 0.9999, 0.9991],
        [0.9933, 0.9999, 0.9997]])
tensor([[0.9820, 0.5000, 0.2689],
        [0.0180, 0.5000, 0.7311]])
tensor([[9., 9., 7.],
        [5., 9., 8.]])
tensor([[1.0000, 1.0000, 1.0000],
        [0.9999, 1.0000, 1.0000]])


## 8. INPLACE OPERATION

In [80]:
m = torch.randint(0, 10, (2,3))
print(m)
n = torch.randint(0, 10, (2,3))
print(n)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [81]:
# in inplace operations, the original tensor is modified in place and the modified tensor is returned
m.add_(n)
print(m)

tensor([[16, 15, 12],
        [ 8,  7, 12]])


## 9. COPYING TENSOR

In [82]:
# we do not use assignment operator for copying tensors, 
# beacuse it will create a reference to the original tensor and when we modify the new tensor,
# the original tensor will also be modified instead we use clone.
print(m)
print(n)

tensor([[16, 15, 12],
        [ 8,  7, 12]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [83]:
m = n.clone()

In [84]:
print(m)
print(n)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [85]:
n[0,0] = 100
print(m)
print(n)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[100,   8,   3],
        [  6,   1,   5]])
