# NN MODULE

The torch.nn module in PyTorch is a core library that provides a wide array of classes and
functions designed to help developers build neural networks efficiently and effectively. It
abstracts the complexity of creating and training neural networks by offering pre-built layers,
loss functions, activation functions, and other utilities, enabling you to focus on designing and
experimenting with model architectures.


Key Components of torch.nn:
1. Modules (Layers):
- nn.Module: The base class for all neural network modules. Your custom models and
layers should subclass this class.

- Common Layers: Includes layers like nn.Linear (fully connected layer), nn.Conv2d (convolutional layer), nn.LSTM (recurrent layer), and many others.

2. Activation Functions:
- Functions like nn.ReLU, nn.Sigmoid, and nn.Tanh introduce non-linearities to the model, allowing it to learn complex patterns.

3. Loss Functions:
- Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss, and nn.NLLLoss to quantify the difference between the model's predictions and the actual targets.

4. Container Modules:
- nn.Sequential: A sequential container to stack layers in order.

5. Regularization and Dropout:
- Layers like nn.Dropout and nn.BatchNorm2d help prevent overfitting and improve the model's ability to generalize to new data.

### *1. Simple Linear Model*

In [2]:
# Create model class 
import torch
import torch.nn as nn

class Model1(nn.Module):
    def __init__(self, num_features):
        super(Model1, self).__init__()  # Call parent constructor
        self.linear = nn.Linear(num_features, 1) # takes input and output number of features.
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out

In [3]:
# Create dataset 
features = torch.randn(10, 5) # generates random values from a normal distribution.

# Create model 
model1 = Model1(features.shape[1])

# Call model for forward pass 
model1(features)  # Calls forward() automatically

tensor([[0.3891],
        [0.5536],
        [0.7578],
        [0.4990],
        [0.5463],
        [0.5466],
        [0.5177],
        [0.5342],
        [0.2421],
        [0.5156]], grad_fn=<SigmoidBackward0>)

In [4]:
# show model weights
model1.linear.bias

Parameter containing:
tensor([-0.1262], requires_grad=True)

In [5]:
pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


In [6]:
from torchinfo import summary
summary(model1, (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### *2. Hidden Layer Model*

In [7]:
class Model2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out


In [19]:
features.shape

torch.Size([10, 5])

In [8]:
# Create dataset 
features = torch.randn(10, 5)

# Create model 
model2 = Model2(features.shape[1]) # passing the columns

# Call model for forward pass 
model2(features)

tensor([[0.4756],
        [0.4888],
        [0.4402],
        [0.4957],
        [0.4900],
        [0.5027],
        [0.5071],
        [0.4393],
        [0.4318],
        [0.5099]], grad_fn=<SigmoidBackward0>)

In [9]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.1587,  0.2619,  0.4098, -0.1845, -0.0357],
        [ 0.3881, -0.4406, -0.2615, -0.3614,  0.0019],
        [ 0.4159, -0.3444,  0.1603, -0.3098, -0.1744]], requires_grad=True)

In [10]:
model2.linear1.bias

Parameter containing:
tensor([-0.4003,  0.3865, -0.0358], requires_grad=True)

In [11]:
summary(model2, (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### *3. Using Container*

In [12]:
class Model3(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [13]:
# Create dataset 
features = torch.randn(10, 5)

# Create model 
model3 = Model3(features.shape[1])

# Call model for forward pass 
model3(features)

tensor([[0.5494],
        [0.4428],
        [0.5302],
        [0.4572],
        [0.4635],
        [0.4635],
        [0.4635],
        [0.4500],
        [0.4635],
        [0.4679]], grad_fn=<SigmoidBackward0>)