# NN MODULE

The torch.nn module in PyTorch is a core library that provides a wide array of classes and
functions designed to help developers build neural networks efficiently and effectively. It
abstracts the complexity of creating and training neural networks by offering pre-built layers,
loss functions, activation functions, and other utilities, enabling you to focus on designing and
experimenting with model architectures.


Key Components of torch.nn:
1. Modules (Layers):
- nn.Module: The base class for all neural network modules. Your custom models and
layers should subclass this class.

- Common Layers: Includes layers like nn.Linear (fully connected layer), nn.Conv2d (convolutional layer), nn.LSTM (recurrent layer), and many others.

2. Activation Functions:
- Functions like nn.ReLU, nn.Sigmoid, and nn.Tanh introduce non-linearities to the model, allowing it to learn complex patterns.

3. Loss Functions:
- Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss, and nn.NLLLoss to quantify the difference between the model's predictions and the actual targets.

4. Container Modules:
- nn.Sequential: A sequential container to stack layers in order.

5. Regularization and Dropout:
- Layers like nn.Dropout and nn.BatchNorm2d help prevent overfitting and improve the model's ability to generalize to new data.

1. Simple Linear Model 

In [40]:
# Create model class 
import torch
import torch.nn as nn

class Model1(nn.Module):
    def __init__(self, num_features):
        super(Model1, self).__init__()  # Call parent constructor
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out

In [41]:
# Create dataset 
features = torch.randn(10, 5)

# Create model 
model1 = Model1(features.shape[1])

# Call model for forward pass 
model1(features)  # Calls forward() automatically

tensor([[0.6199],
        [0.4429],
        [0.4879],
        [0.5684],
        [0.5144],
        [0.3479],
        [0.3235],
        [0.4657],
        [0.4461],
        [0.6174]], grad_fn=<SigmoidBackward0>)

In [42]:
# show model weights
model1.linear.bias

Parameter containing:
tensor([-0.1423], requires_grad=True)

In [35]:
pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


In [43]:
from torchinfo import summary
summary(model1, (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

2. Hidden Layer Model 

In [44]:
class Model2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out


In [45]:
# Create dataset 
features = torch.randn(10, 5)

# Create model 
model2 = Model2(features.shape[1])

# Call model for forward pass 
model2(features)

tensor([[0.4077],
        [0.4557],
        [0.4557],
        [0.4218],
        [0.4296],
        [0.3859],
        [0.3990],
        [0.3979],
        [0.3996],
        [0.3600]], grad_fn=<SigmoidBackward0>)

In [46]:
model2.linear1.weight

Parameter containing:
tensor([[-0.4085,  0.3550, -0.2741,  0.2795,  0.2734],
        [ 0.2854,  0.3125,  0.3224,  0.1665, -0.2969],
        [ 0.0567,  0.3303,  0.4181,  0.1531,  0.1267]], requires_grad=True)

In [48]:
model2.linear1.bias

Parameter containing:
tensor([-0.2047,  0.1370,  0.0583], requires_grad=True)

In [49]:
summary(model2, (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

3. Using Container

In [52]:
class Model3(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [53]:
# Create dataset 
features = torch.randn(10, 5)

# Create model 
model3 = Model3(features.shape[1])

# Call model for forward pass 
model3(features)

tensor([[0.4647],
        [0.4647],
        [0.4647],
        [0.4870],
        [0.4647],
        [0.5048],
        [0.4647],
        [0.4684],
        [0.4056],
        [0.5113]], grad_fn=<SigmoidBackward0>)